version: '2'
services:
  seafile-client:
    restart: always
    image: gronis/seafile-client
    container_name: seafile-client
    environment:
      - LIBRARY_ID=<your-library-id-here>
      - SERVER_URL=<server-url>
      - SERVER_PORT=<server-port>
      - USERNAME=<username>
      - PASSWORD=<password>
      - DATA_DIR=<directory-path-to-sync>
    volumes:
      - <host-volume-path>:<directory-path-to-sync>
